services:
  frontend:
    image: ursulaonyi/dream-vacation-frontend-2:latest
    ports:
      - "3000:3000"
    env_file:
      - .env

  backend:
    image: ursulaonyi/dream-vacation-backend-2:latest
    ports:
      - "3001:3000"
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
