name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-backend:latest

    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-frontend:latest

    - name: SSH and deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/Dream-Vacation-App
          docker-compose down --remove-orphans
          docker system prune -af
          docker-compose pull
          docker-compose up -d
