name: Test Docker Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: test-backend:latest
          no-cache: true

      - name: Build frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: test-frontend:latest
          no-cache: true

      - name: Run backend container for tests
        run: |
          docker run --rm test-backend:latest npm test

      - name: Run frontend container for tests
        run: |
          docker run --rm test-frontend:latest npm test
